name: first workflow
on:fdfdddd
  # workflow_dispatch:
  #   inputs:
  #     versionName:
  #       required: true
  #       description: "this is version name for github workflow"
  # repository_dispatch:
  #   types: [test]
   push:
  #   branches:
  #     - "main"
  #     - "feat/**"
  #   paths:
  #     - "app/**"
  # pull_request:
  #   branches-ignore:
  #     - "feature/**"
  #   types: [opened, closed]
jobs:
  first-workflow-job:
    name: first job
    runs-on: ubuntu-latest
    container: 
      image: node:14.16
    steps:
      - name: check node version
        run: node -v
      - name: before checkout action
        if: github.ref == 'refs/head/feature'
        run: ls
        shell: bash

      - name: checkout steps
        uses: actions/checkout@v4
        
      - name: after checkout action
        # if: github.event.inputs.versionName == 'test'
        run: ls
        shell: bash
